config/routes.rb
Wierszopis::Application.routes.draw do |map|
  resources :profiles
  resources :users do
    resources :chapters
  end
  resources :chapters
  resources :credits
  resources :poems do
    resources :comments
  end

  post '/poems/find', to: 'poems#find' #akcja 'find'
  get '/poems/index', to: 'poems#index'

  resource :session

  # strona glowna
  root to: 'poems#index'

	# kanal rss
  get '/rss.xml', to: 'poems#rss'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'

end

app/models/poem.rb
class Poem < ActiveRecord::Base
  has_attached_file :mp3
  has_attached_file :mp3, :path => ":rails_root/public/audios/:id/:basename.:extension"

  # paginacja
  cattr_reader :per_page
  @@per_page = 5

  # model dependencies
  belongs_to :user, required: true
  belongs_to :chapter, required: true
  has_many :comments, -> { order('created_at DESC') }, dependent: :destroy

  # validators
  validates :title, :presence => true
  validates :body, :presence => true

  scope :recent, lambda { |term| order("poems.created_at DESC").limit("#{term}") }

  def owned_by?(current_user)
    return false if current_user.nil?
    current_user.id == user_id
  end

  def author
    user&.profile&.full_name || 'unknown'
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :authenticate, :except => [:index, :show, :rss, :find]

  # GET /poems
  # GET /poems.xml
  def index

    # wczesniejszy sposob wyswietlania wierszy
    # @poems = Poem.all

    # wyswietlani wierszy z paginacja
    @poems = Poem.order('created_at DESC').paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @poems }
      format.rss
    end
  end

  # kanal RSS
  def rss
    @poems = Poem.find(:all, :order => "id DESC", :limit => 10)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end


  # GET /poems/1
  # GET /poems/1.xml
  def show
    @poem = Poem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @poem }
    end
  end

  # GET /poems/new
  # GET /poems/new.xml
  def new
    @poem = Poem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @poem }
    end
  end

  # GET /poems/1/edit
  def edit
    @poem = current_user.poems.find(params[:id])
    unless @poem.owned_by?(current_user)
      redirect_to(poems_path, :alert => 'Nie jestes autorem tego wiersza!')
    end
  end

  # POST /poems
  # POST /poems.xml
  def create
    @poem = current_user.poems.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to(@poem, :notice => 'Utworzono wiersz.') }
        format.xml  { render :xml => @poem, :status => :created, :location => @poem }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @poem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /poems/1
  # PUT /poems/1.xml
  def update
    @poem = current_user.poems.find(params[:id])
    unless @poem.owned_by?(current_user)
      redirect_to(poems_path, :alert => 'Nie jestes autorem tego wiersza!')
    end


    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to(@poem, :notice => 'Zaktualizowano wiersz.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @poem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.xml
  def destroy
    @poem = current_user.poems.find(params[:id])
    unless @poem.owned_by?(current_user)
      redirect_to(poems_path, :alert => 'Nie jestes autorem tego wiersza!')
    else
      @poem.destroy

      respond_to do |format|
        format.html { redirect_to(poems_url, :notice => 'Usunieto wiersz') }
        format.xml  { head :ok }
      end
    end
  end

  def find
    @found_poems = Poem.where("title LIKE ?", "%#{params[:search_string]}%")
  end

  private

  def poem_params
    params.require(:poem).permit(:title, :body, :chapter_id, :composed_at, :tag_list) # Add any other permitted parameters here
  end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_form.html.erb
<%= form_for(@poem, :html => { :multipart => true}) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
	<font color="red"><h4>Oj, liczba błędów: <%= pluralize(@poem.errors.count, "error") %></h4>

      <ul>
      <% @poem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </font>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Tytuł" %><br />
    <%= f.text_field :title %>
  </div>
  <br/>

  <div class="field">
    <%= f.label "Treść" %><br />
    <%= f.text_area :body, :size => "70x20" %>
  </div>
  <br/>

  <div class="field">
    <%= f.label "Rodział" %><br />
    <%= select_tag "poem_chapter_id",
    options_from_collection_for_select(current_user.chapters.all,
    'id', 'name', @poem.chapter_id),:include_blank => true, :name => "poem[chapter_id]"  %>
    <%= link_to image_tag("add_chapter.png"), new_chapter_path %>
  </div>
  <br/>

  <div class="field">
    <%= f.label "Napisany:" %><br />
    <%= f.date_select :composed_at, :order => [:day, :month, :year],
    :start_year => Time.now.year - 100, :end_year => Time.now.year %>
  </div>
  <div class="field">
    <%= f.label :mp3 %><br />
    <%= f.file_field :mp3 %>
  </div>
  <br/>
  <br/>

  <div class="actions">
    <%= image_submit_tag("accept.png") %> (akceptuj) <br/>
    <a href="javascript:history.go(-1);"><%= image_tag 'back.png' %></a> (powrót) <br/>
    <%= link_to image_tag("index.png"), poems_path %> (spis wszystkich)
  </div>
  <br/>

<% end %>

app/views/poems/_poem.html.erb
<%= tag.div id: dom_id(poem), class: dom_class(poem) do %>
<h3>
  <%= link_to poem.title, poem %>
  <span class='author'>
    <%= poem.author %>
  </span>
  <% if poem.owned_by? current_user %>
  <span class='actions'>
    <%= link_to "Edit", edit_poem_path(poem) %>
    <%= link_to "Delete", poem, data: { confirm: "Are you sure?" }, method: :delete %>
  </span>
  <% end %>
</h3>
<%= simple_format poem.body %>
<% end %>

app/views/poems/edit.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'application' %>

    <script type="text/javascript">
	
			tinyMCE.init({
					// General options
					mode : "textareas",
					theme : "advanced",
					plugins : "pagebreak,style,layer,advhr,advimage,advlink,emotions,inlinepopups,insertdatetime,preview,searchreplace,print,contextmenu,paste,directionality,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

					// Theme options
					theme_advanced_buttons1 : "newdocument,formatselect,|,bold,italic,|,charmap,emotions,image,code,|",
					theme_advanced_buttons2 : "search,replace,|blockquote,|,undo,redo,|,link,unlink,|,insertdate,inserttime,preview,print",
					theme_advanced_buttons3 : "",
					theme_advanced_buttons4 : "",
					theme_advanced_toolbar_location : "top",
					theme_advanced_toolbar_align : "left",
					theme_advanced_statusbar_location : "bottom",
					theme_advanced_resizing : false,

					// Example content CSS (should be your site CSS)
					content_css : "css/content.css",

					// Drop lists for link/image/media/template dialogs
					template_external_list_url : "lists/template_list.js",
					external_link_list_url : "lists/link_list.js",
					external_image_list_url : "lists/image_list.js",

					// Style formats
					style_formats : [
						{title : 'Bold text', inline : 'b'},
						{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
						{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
						{title : 'Example 1', inline : 'span', classes : 'example1'},
						{title : 'Example 2', inline : 'span', classes : 'example2'},	
					],

				});
		</script>

<% end %>

<h2>Edytuj wiersz</h2>

<%= render 'form' %>

app/views/poems/find.html.erb
<h2>Rezultat wyszukiwania:</h2>


<table width="560">
  <tr>
    <th width="160px">Tytuł</th>
    <th width="160px">Autor</th>
    <th width="160px">Napisany</th>
    <th></th>
    <th></th>
    <th>Opcje</th>
  </tr>

<% for poem in @found_poems %>

  <%= tag.div id: dom_id(poem), class: dom_class(poem) do %>

	<tr>
    <td width="160px" align="center"><%= link_to poem.title, poem %></td>
    <td width="160px" align="center"><%= poem.author %></td>
    <td width="160px" align="center"><%= poem.composed_at %></td>	

		<td width="200px"></td>

    <td><%= link_to image_tag("show.png"), poem_path(poem) %></td>

		<% if poem.owned_by? current_user %>

    <td><%= link_to image_tag("edit.png"), edit_poem_path(poem) %></td>
    <td><%= link_to image_tag("delete.png"), poem, :confirm => "Usunąć wiersz?", :method => :delete %></td>

		<% end %>
  </tr>


	<% end %>
	
<% end %>

</table>

app/views/poems/index.html.erb
<h2>Wszystkie wiersze</h2>

<div id="poems">


<table width="560">
		<tr>
		  <th width="160px">Tytuł</th>
		  <th width="160px">Autor</th>
		  <th width="160px">Rozdział</th>
		  <th width="160px">Napisany</th>
		  <th></th>
		  <th></th>
		  <th>Opcje</th>
		</tr>
	<% @poems.each do |poem| %>
		<tr>
		  <td width="160px" align="center"><%= poem.title %></td>
		  <td width="160px" align="center"><%= poem.author %></td>
		  <td width="160px" align="center"><%= if
		  !poem.chapter.nil? then poem.chapter.name else "" end %></td>
		  <td width="160px" align="center"><%= poem.composed_at %></td>	
			<td width="200px"></td>
		  <td><%= link_to image_tag("show.png"), poem_path(poem) %></td>
		 <% if poem.owned_by? current_user %>
		  <td><%= link_to image_tag("edit.png"), edit_poem_path(poem) %></td>
		  <td><%= link_to image_tag("delete.png"), poem, :confirm => "Usunąć wiersz?", :method => :delete %></td>
		 <% end %>
		</tr>
	<% end %>
</table>

<hr size="1" width="100" align="center"/>
<div class="editedText"><div class="flickr_pagination"><center><%= will_paginate @poems %></center></div></div>

</div>

<br />

<p>
   <%= link_to image_tag("add.png"), new_poem_path %>  (dodaj)
   <% unless @current_user.nil? %>
   <%= link_to image_tag("chapters.png"), chapters_path %>
   <% end %>
</p>

<br />

app/views/poems/new.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'application' %>

    <script type="text/javascript">
	
			tinyMCE.init({
					// General options
					mode : "textareas",
					theme : "advanced",
					plugins : "pagebreak,style,layer,advhr,advimage,advlink,emotions,inlinepopups,insertdatetime,preview,searchreplace,print,contextmenu,paste,directionality,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

					// Theme options
					theme_advanced_buttons1 : "newdocument,formatselect,|,bold,italic,|,charmap,emotions,image,code,|",
					theme_advanced_buttons2 : "search,replace,|blockquote,|,undo,redo,|,link,unlink,|,insertdate,inserttime,preview,print",
					theme_advanced_buttons3 : "",
					theme_advanced_buttons4 : "",
					theme_advanced_toolbar_location : "top",
					theme_advanced_toolbar_align : "left",
					theme_advanced_statusbar_location : "bottom",
					theme_advanced_resizing : false,

					// Example content CSS (should be your site CSS)
					content_css : "css/content.css",

					// Drop lists for link/image/media/template dialogs
					template_external_list_url : "lists/template_list.js",
					external_link_list_url : "lists/link_list.js",
					external_image_list_url : "lists/image_list.js",

					// Style formats
					style_formats : [
						{title : 'Bold text', inline : 'b'},
						{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
						{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
						{title : 'Example 1', inline : 'span', classes : 'example1'},
						{title : 'Example 2', inline : 'span', classes : 'example2'},	
					],

				});
		</script>

<% end %>

<h2>Dodaj wiersz</h2>

<%= render 'form' %>

app/views/poems/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'audiojs/audio.min.js' %>

	<script>
		audiojs.events.ready(function() {
		  var as = audiojs.createAll();
		});
	</script>

<% end %>

<h2>Utwór pt. <i>"<%= @poem.title %>"</i></h2>

<div class="edite</p>dText">
  <table>
    <tr>
      <td>
	<center><%= simple_format @poem.body %></center>
      </td>
    </tr>
  </table>
</div>

<br/>

<hr size="1" width="200" align="left"/>

<p>Utworzono: <%= @poem.composed_at %></p>

<p>
  <a href="javascript:history.go(-1);"><%= image_tag 'back.png' %></a> (powrót) <br/>
  <%= link_to image_tag("edit.png"), edit_poem_path(@poem) %> (edytuj) <br/>
  <%= link_to image_tag("index.png"), poems_path %> (spis wszystkich)
</p>

<br/>
<br/>
<br/>

<% if !@poem.mp3_file_name.nil? %>

	<h4>
		<audio src="/audios/<%= @poem.id.to_s + "/" + @poem.mp3_file_name %>" preload="auto" />
	</h4>

	<!-- Stara wersja odtwarzacza	
		<h4>
			<%= audio_tag(@poem.id.to_s + "/" + @poem.mp3_file_name, :autoplay => true, :controls => true)  %>
		</h4>
	-->
<% end %>
<br />

<h4><u><i>Komentarze</i></u></h4>

<div id="comments">
  <%= render @poem.comments %>
</div>

<%= link_to "Napisz komentarz!", new_poem_comment_path(@poem, :format => :js), :remote => true, :id => 'new_comment_link' %>