config/routes.rb
Wierszopis::Application.routes.draw do |map|
  resources :profiles
  resources :users do
    resources :chapters
  end
  resources :chapters
  resources :credits
  resources :poems do
    resources :comments
  end

  post '/poems/find', to: 'poems#find' #akcja 'find'
  get '/poems/index', to: 'poems#index'

  resource :session

  # strona glowna
  root to: 'poems#index'

	# kanal rss
  get '/rss.xml', to: 'poems#rss'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base

  # model dependencies
  belongs_to :user
  has_many :poems, -> { order('created_at DESC, composed_at DESC, name ASC') }, dependent: :nullify

  # validators

  validates :name, presence: true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  # GET /chapters
  # GET /chapters.xml
  def index
    @chapters = current_user.chapters.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chapters }
    end
  end

  # GET /chapters/1
  # GET /chapters/1.xml
  def show
    @chapter = Chapter.find(params[:id])
    @poems = Poem.find_by(chapter: @chapter) || []

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.xml
  def new
    @chapter = Chapter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
  end

  # POST /chapters
  # POST /chapters.xml
  def create
    @chapter = Chapter.new(chapter_params)
    @chapter.user_id = current_user.id

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to(@chapter, :notice => 'Utworzono rozdzial.') }
        format.xml  { render :xml => @chapter, :status => :created, :location => @chapter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chapter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.xml
  def update
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        format.html { redirect_to(@chapter, :notice => 'Zaktualizowano rozdzial.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chapter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.xml
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to(chapters_url) }
      format.xml  { head :ok }
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name, :description)
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <font color="red"><h4>Oj, liczba błędów: <%= pluralize(@chapter.errors.count, "error") %></h4>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
     </font>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nazwa" %><br />
    <%= f.text_field :name %>
  </div>
  <br/>

  <div class="field">
    <%= f.label "Opis"	 %><br />
    <%= f.text_area :description, :size => "70x20" %>
  </div>
  <br/>

  <div class="actions">
    <%= image_submit_tag("accept.png") %> (akceptuj) <br/>
    <a href="javascript:history.go(-1);"><%= image_tag 'back.png' %></a> (powrót) <br/>
    <%= link_to image_tag("index.png"), poems_path %> (spis wszystkich)
  </div>
  <br/>

<% end %>

app/views/chapters/edit.html.erb
<h2>Edytuj rodział</h2>

<%= render 'form' %>

app/views/chapters/index.html.erb
<h2>Rodziały</h2>

<div id="poems">



<table width="560">
  <tr>
    <th width="160px">Rodział</th>
    <th width="160px">Opis</th>
    <th></th>
    <th></th>
    <th>Opcje</th>
  </tr>

<% @chapters.each do |chapter| %>
  <tr>
    <td width="160px" align="center"><%= chapter.name %></td>
    <td width="160px" align="center"><%= chapter.description %></td>
	<td width="200px"></td>
    <td>   <%= link_to image_tag("show.png"), user_chapter_path(current_user, chapter) %></td>
    <td>   <%= link_to image_tag("edit.png"), edit_user_chapter_path(current_user, chapter) %></td>
    <td>   <%= link_to image_tag("delete.png"), user_chapter_path(current_user, chapter), :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>

</table>

</div>

<br />

<p>
   <%= link_to image_tag("add.png"), new_user_chapter_path(current_user) %> (dodaj)
</p>

<br />

app/views/chapters/new.html.erb
<h4>Nowy rozdział</h4>

<%= render 'form' %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Rodział <i>"<%= @chapter.name %>"</i></h2>

<p>
  <b>Nazwa:</b>
  <%= @chapter.name %>
</p>

<p>
  <b>Opis:</b>
  <%= @chapter.description %>
</p>

<p>
  <b>Zawiera wiersze:</b>
  <% @poems.each do |p| %>
   <li><%= link_to p.title, poem_path(p) %></li>
  <% end %>
</p>


<br/>
<hr size="1" width="200" align="left"/>
<p>Utworzono: <%= @chapter.created_at %></p>
<p><a href="javascript:history.go(-1);"><%= image_tag 'back.png' %></a> (powrót) <br/>
<%= link_to image_tag("edit.png"), edit_chapter_path(@chapter) %> (edytuj) <br/>
<%= link_to image_tag("index.png"), chapters_path %> (spis wszystkich)