config/routes.rb
Wierszopis::Application.routes.draw do |map|
  resources :profiles
  resources :users do
    resources :chapters
  end
  resources :chapters
  resources :credits
  resources :poems do
    resources :comments
  end

  post '/poems/find', to: 'poems#find' #akcja 'find'
  get '/poems/index', to: 'poems#index'

  resource :session

  # strona glowna
  root to: 'poems#index'

	# kanal rss
  get '/rss.xml', to: 'poems#rss'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>	
    <title>Wierszopis</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'jquery-1.4.4.min', 'rails' %>
    <%= yield :javascript_includes %>
    <%= csrf_meta_tag %>
    <link rel="icon" href="images/favicon.ico" />
    <link rel="alternate" type="application/rss+xml" title="RSS" href="/poems/" />
  </head>
  <body>
    <div id="templatemo_wrapper_01">
      <div id="templatemo_wrapper_02">

        <div id="templatemo_header">
    	  <div id="site_title">
	    <% if logged_in? %>
	    
	    <a href="/poems"><strong><i><%= current_user.nickname + "," + " wyraź siebie!" %></i></strong>
	      <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fsigma.ug.edu.pl%3A8064&amp;layout=button_count&amp;show_faces=true&amp;width=400&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:400px; height:21px;" allowTransparency="true">
	      </iframe>
	    </a>

	    <% else %>		

	    <a href="/poems"><i>Wyraź siebie...</i>
	      <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fsigma.ug.edu.pl%3A8064&amp;layout=button_count&amp;show_faces=true&amp;width=400&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:400px; height:21px;" allowTransparency="true">
	      </iframe>
	    </a>

	    <% end %>
            
          </div>
          
          <div id="header_right">
            
            <!-- <a href="#" class="button twitter"></a> -->
            <a href="mailto:wierszopis@wierszopis.pl" class="button mail"></a>
            <a href="/rss.xml" class="button rss"></a>
            
            <div id="search_box">
              <!-- NOWA WERSJA WYSZUKIWANIA -->
              <%= form_with url: "/poems/find", local: true do %>
              <%= text_field_tag :search_string, "Szukaj tytuł...", :onfocus=>"if(this.value=='Szukaj tytuł...')this.value='';"  %>
              <%= image_submit_tag ("search.png")%>
              <% end %>
              <!-- STARA WERSJA WYSZUKIWANIA
                   <form action="#" method="get">
                     <input type="text" value="Szukaj w serwisie..." name="q" size="10" id="searchfield" 
			    title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                     <input type="submit" name="Search" value="" id="searchbutton" title="Search" />
                   </form>
                   -->
            </div>
            
            <div id="templatemo_menu">
              <ul>

		<% if logged_in? %>

		<li><%= link_to "Wyloguj", logout_path %></li>
		<li><%= link_to "Profil", profile_path(current_user) %></li>
		<li><%= link_to "Wiersze", poems_path %></li>
		<li><%= link_to "Rozdziały", user_chapters_path(current_user) %></li>

		<% else %>

                <li><%= link_to "Logowanie", login_path %></li>
                <li><%= link_to "Rejestracja", new_user_path %></li>

		<% end %>
		
                <li><%= link_to "O serwisie", "/credits/show" %></li>

              </ul>    	
            </div> <!-- end of templatemo_menu -->        
          </div>
        </div> <!-- end of templatemo_header -->
        
        
        <div id="templatemo_main">
    	  
          <div id="templatemo_content_wrapper">
            <div id="templatemo_content_top"></div>
            <div id="templatemo_content">
              
              <div class="content_box">
                
                <!-- komunkaty błędów -->
                <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
                <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
	        
	        <%= yield %>
              </div>
	      

            </div> <!-- end of content -->
            <div id="templatemo_content_bottom"></div>
          </div> <!-- end of content wrapper -->
          
          <div id="templatemo_sidebar">
            
            <div class="sidebar_box_wrapper">

              <% if logged_in? %>                  
              <div class="sidebar_box">
                <div class="sb_title"><%= image_tag 'user_panel.png' %></div>
                <div class="sb_content">
                  <div class="user_content">
                    <%= image_tag avatar_url(current_user), :align => :top %>
                    <ul>
                      <li><%= current_user.full_name %>,</li>
                      <li><%= current_user.profile.place %></li>
                    </ul>
                  </div>
                </div>
              </div>
              <% end %>

              
              
              <% if logged_in? %>                  
            <div class="sidebar_box">
              <div class="sb_title"><%= image_tag 'categories.png' %></div>
              <div class="sb_content">
                <ul class="tmo_list">

		  <!-- Listowanie rodziałów, problem, kiedy nie jest
		       sie na rodzialach -->
		  <% user_chapters(current_user).each do |chapter| %>
		     <li><%= link_to chapter.name, user_chapter_path(current_user, chapter) %></li>
		     <% end %>
                </ul>	
              </div>
            </div>
            <% end %>
            
            <div class="sidebar_box">
                <div class="sb_title"><%= image_tag 'recent_blog_entries.png' %></div>
                <div class="sb_content">
                  <ul class="tmo_list">
                    <% recent_poems.each do |p| %>
                    <li><%= link_to p.title, poem_path(p) %></li>
                    <% end %>
                  </ul>	
                </div>
              </div>
            
            </div>
            
            
	    <div class="templatemo_cleaner"></div>            

            <div class="templatemo_sidebar_bottom"></div>
	    
	    <div class="templatemo_cleaner"></div>
            
	    <div>
              <a href="#" class="ads_125"><%= image_tag 'ads_125.jpg' %></a>
              <a href="#" class="ads_125"><%= image_tag 'ads_125.jpg' %></a>
              <a href="#" class="ads_125"><%= image_tag 'ads_125.jpg' %></a>
              <a href="#" class="ads_125"><%= image_tag 'ads_125.jpg' %></a>			
	    </div>

	    <div class="templatemo_cleaner"></div>
	    
	    <div align="center">
	      <!-- <a href="http://validator.w3.org/check?uri=referer">
		   <img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" 
			alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" />
	      </a> 
	      &nbsp;&nbsp;&nbsp;
	      <a href="http://jigsaw.w3.org/css-validator/check/referer">
		<img style="border:0;width:88px;height:31px"  src="http://jigsaw.w3.org/css-validator/images/vcss-blue" 
		     alt="Valid CSS!" vspace="8" border="0" />
	      </a> -->
	    </div>
            
          </div> <!-- end of sidebar -->
          
    	  <div class="clear"></div>
        </div> <!-- end of main -->
        
        <div id="templatemo_footer">
    	  Copyright © 2011 | Powered by <a href="http://wierszopis.art.pl">Wierszopis</a> | 
	  Daniel Landowski, Artur Rybak, Łukasz Kępiński | ASI - 12.01.2011r.
        </div> <!-- end of footer -->
        
      </div> <!-- end of wrapper 02 -->
    </div> <!-- end of wrapper 01 -->
  </body>
</html>

app/views/layouts/application_old_and_default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wierszopis</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag 'jquery-1.4.4.min', 'rails', 'application' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="header">
      <h1><%= link_to "Wierszopis", root_path %></h1>
      <div id="user_bar">
        <%= link_to "All Poems", poems_path %> |
        <% if logged_in? %>
        <%= link_to "Chapters", user_chapters_path(current_user)  %> |
        <%= link_to "New Poem", new_poem_path %> |
        <%= link_to "Account", user_path(current_user) %> |
        <%= link_to "Profile", profile_path(current_user) %> |
        <%= link_to "Logout", logout_path %>
         <span style="display:block;">
           Witaj <strong><%= current_user.nickname + "! <" +
           current_user.full_name + ">" %></strong>
         </span>
        <% else %>
        <%= link_to "Login", login_path %> or 
        <%= link_to "Register", new_user_path %>
        <% end %>
      </div>
    </div>
    <div id="main">

    <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
    <%= content_tag :p, alert, :class => 'alert' if alert.present? %>

    <%= yield %>

    </div>
    <div id="footer">Powered by <a href="http://wierszopis.art.pl">Wierszopis</a></div>

  </body>
</html>